import numpy as np
arr1=np.array([[1,2],[3,4]])
print("first array")
print(arr1)
arr2=np.array([[11,12],[13,14]])
print("second array")
print(arr2)
result=np.multiply(arr1,arr2)
print("result is")
print(result)
